[project]
name = "LoopFiX"
description = "AI-powered DeFi savings vaults on Bitcoin (Stacks)"
authors = ["Juggernaut7"]
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.AdvisorNFT]
path = "contracts/AdvisorNFT.clar"
clarity_version = 2

[contracts.GroupVault]
path = "contracts/GroupVault.clar"
clarity_version = 2

[contracts.SavingsVault]
path = "contracts/SavingsVault.clar"
clarity_version = 2
