[project]
name = "loopfix"
requirements = []
[contracts.advisor-nft]
path = "contracts/AdvisorNFT.clar"
[contracts.group-vault]
path = "contracts/GroupVault.clar"
[contracts.savings-vault]
path = "contracts/SavingsVault.clar"
