[project]
name = "loopfix"
description = "AI-powered DeFi savings vaults on Bitcoin (Stacks)"
authors = ["LoopFi Team"]
telemetry = false
cache_dir = ".cache"
requirements = []
[project.costs]
large_contract = 100000
[project.analysis]
passes = ["check_checker"]

[contracts.savings-vault]
path = "contracts/SavingsVault.clar"
clarity_version = 2
epoch = 2.4

[contracts.group-vault]
path = "contracts/GroupVault.clar"
clarity_version = 2
epoch = 2.4

[contracts.advisor-nft]
path = "contracts/AdvisorNFT.clar"
clarity_version = 2
epoch = 2.4
